# Generated by Django 4.0.3 on 2022-03-27 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='menu',
            new_name='workout',
        ),
    ]
