# Generated by Django 4.0.4 on 2022-04-12 12:11

from django.conf import settings
from django.db import migrations, models
import workout_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0002_rename_menu_workout_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=workout_app.models.User, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー名'),
        ),
    ]
