# Generated by Django 4.0.4 on 2022-05-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0003_alter_workout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutdetail',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='日付'),
        ),
    ]
