# Generated by Django 4.0.4 on 2022-05-05 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0004_alter_workoutdetail_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutdetail',
            name='date',
        ),
    ]
